"""change CreditCard Store many to many relationship

Revision ID: 0e5a0467e7e1
Revises: 68b8dd90d274
Create Date: 2023-10-13 00:48:11.197023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5a0467e7e1'
down_revision = '68b8dd90d274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores_credit_cards',
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], name=op.f('fk_stores_credit_cards_credit_card_id_credit_cards')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_stores_credit_cards_store_id_stores'))
    )
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credit_cards_store_id_stores', type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_credit_cards_store_id_stores', 'stores', ['store_id'], ['id'])

    op.drop_table('stores_credit_cards')
    # ### end Alembic commands ###
