"""remove card_name store_name column constrains

Revision ID: 68b8dd90d274
Revises: b21443a67857
Create Date: 2023-10-05 20:57:00.990496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b8dd90d274'
down_revision = 'b21443a67857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.alter_column('card_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('store_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('expire_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('expire_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('store_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.alter_column('card_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
