"""create many to many relationshhip

Revision ID: b21443a67857
Revises: 1207c21905f7
Create Date: 2023-10-05 14:26:10.099407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21443a67857'
down_revision = '1207c21905f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('discount', sa.String(), nullable=True),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_credit_cards_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_cards_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_cards'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_cards')
    op.drop_table('stores')
    # ### end Alembic commands ###
